

/**
 * Beobachter.java
 *
 * @author (your name) 
 * @version (a version number or a date)
 */


/**
 * 
 */
public interface Beobachter
{

    public void addObserver(Zuschauer o);
    
    public void removeObserver(Zuschauer o);
    
    public void notifyObservers();
    
    public int getState();
    
    public void setState(int state);
}

/*
 *Source file generated by patternCoder for BlueJ Version 0.5.3.004.
 *For more info, please visit http://www.patterncoder.org.
 */